import './globals.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ 
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ["400"]
})

export const metadata = {
  title: 'Kelly Caldwell and Kashmere',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans`}>{children}</body>
    </html>
  )
}
